stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "website2"

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t website2 .
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker stop website2 || true
    - docker rm website2 || true
    - docker run -d -p 8000:80 --name website2 website2
  only:
    - main
